Table users {
  id integer [primary key]
  username string
  email string
  password string
}

Table tasks {
  id integer [primary key]
  title string
  body string
  link string
  user_id integer [not null]
  end string
  push_id integer [not null]
  subtasks_id list_integer [not null]
  group_id integer [not null]
}

Table subtasks {
    id integer [primary key]
    title string
    body string
    link string
}

Table pushes {
    id integer [primary key]
    name string
    minutes integer
    hours integer
    days integer
    sound boolean
}

Table groups {
    id integer [primary key]
    name string
    description string
    colour string
}

Ref user_tasks: tasks.user_id > users.id // many-to-one
Ref task_sub: tasks.subtasks_id <> subtasks.id // many-to-many
Ref task_push: tasks.push_id > pushes.id // many-to-one
Ref task_group: tasks.group_id > groups.id // many-to-one
